cds:
  key1: value1
  key2: value2
ss:
  key1: value1
  key2: value2
rs:
  key1: value1
  key2: value2

spring:
  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1
